spring:
  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/646e2152-52af-462f-b278-f26c7098ffe3/v2.0
            user-name-attribute: name
        registration:
          azure-dev:
            provider: azure
            client-id: "818f3e78-5e4b-4b0b-86e2-a31e5e3650c8"
            client-secret: "EVI8Q~k43ErUISxQAtmN8bfLrPHEUQNNlr7oIa6O"
            scope:
              - openid
              - email
              - profile

# Group mapping
codeland:
  jwt:
    authorization:
      group-to-authorities:
        "ceef656a-fca9-49b6-821b-f7543b7065cb": BAELDUNG_RW
        "eaaecb69-ccbc-4143-b111-7dd1ce1d99f1": BAELDUNG_RO,BAELDUNG_ADMIN
